### PR TITLE
Smart Glasses

### PR DESCRIPTION
**Pull request by Ashishkumarpanda**
Smart glasses.
it consists of 
1)Arduino nano
2)Hc05 ultrasonic sensor
it can be used by blind people to walk in road because it will alert them when an object will come in a given radius that is set by the programmer as per day-to-day life scenario.

WhatsApp Image 2020-09-26 at 9 03 05 PM

### CODE REVIEW

**Comment by Hyper-Matrix** [comment]
@Ashishkumarpanda Great project. Thank you so much for contributing.
It would be great if you could include a readme file so as to let the users know more about this project.

**Review by rupeshmohanty — APPROVED** [review]
This looks like an awesome project!

**Comment by AshutoshGeek** [comment]
Good project.

**Review by AshutoshGeek — APPROVED** [review]
Looks good project. Do add comment lines describing the function of the code.

**Review by C3Suryansu — APPROVED** [review]
Awesome Project!

**Pull request merged**
